config/routes.rb
OrcamentoControlIfba::Application.routes.draw do

  devise_for :users
  
  resources :home do 
    get :rectory_index, :on => :collection
    get :unit_index, :on => :collection
  end
  resources :resources do
    
    get :detail, :to => "resources#detail"
    
    resources :devolutions
    
    resources :transfers do
      
      resources :devolution_transfers
      
      resources :effort_transfers do
        resources :payment_transfers
      end
    end
    
    resources :efforts do
      resources :payments
    end
  end
  
  resources :budgets

  resources :natures

  resources :units
  root :to => "home#index"
  
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  
  attr_accessible :end_date, :nc_number, :start_date, :resources_attributes
  has_many :resources, :dependent => :destroy
  accepts_nested_attributes_for :resources
  
  validates_presence_of :nc_number, :message => " deve ser preenchido"
  validates_presence_of :start_date, :message => " deve ser preenchido"
  validates_presence_of :end_date, :message => " deve ser preenchido"
  validates_presence_of :resources, :message => " deve ser preenchido"
  
  
  def total
    
    total_value = 0
    
    for resource in resources
      total_value = total_value + resource.value
    end
    
    total_value
  end
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController


  def index
    @budgets = Budget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @budgets }
    end
  end

  
  def show
    @budget = Budget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @budget }
    end
  end


  def new
    @budget = Budget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @budget }
    end
  end

  def edit
    @budget = Budget.find(params[:id])
  end

  def create
    @budget = Budget.new(params[:budget])

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render json: @budget, status: :created, location: @budget }
      else
        format.html { render action: "new" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @budget = Budget.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/budgets_helper.rb
#encoding: utf-8
module BudgetsHelper
  
   def translate_bg_attr(name)
     
      attr = name.to_s
      case attr
      when "nc_number"
        attr = "O Nº da NC"
      when "start_date"
        attr = "A Data início"
      when "end_date"
        attr = "A Data final"
      when "resources"
        attr = "Recursos"
      end
    
     attr
    
  end
  
end

app/views/budgets/_form.html.erb
<%=  javascript_tag  do%>
	
	jQuery(function($) {
		
	    $('#budget_start_date').datepicker({
    		  yearRange     : 'c-0:c+10',
      		  showButtonPanel  : false,
      		  numberOfMonths  : 1,
      		  stepMonths    : 1,
	  		  dateFormat : 'dd/mm/yy',
      		  hideIfNoPrevNext: true
    	});
	
		$('#budget_end_date').datepicker({
    		  yearRange     : 'c-0:c+10',
      		  showButtonPanel  : false,
      		  numberOfMonths  : 1,
      		  stepMonths    : 1,
	  		  dateFormat : 'dd/mm/yy',
      		  hideIfNoPrevNext: true
    	});
	
	
});
	
	
<%end%>


<%= nested_form_for(@budget,:html =>{:class => "well form-horizontal"}) do |f| %>
  
  
  <% if @budget.errors.any? %>
		<div class="alert alert-error">
			<a class="close" data-dismiss="alert" href="#">×</a>
			<ul class="unstyled">
				<% @budget.errors.each do |attribute,msg| %>
						<li> <%=translate_bg_attr(attribute) + msg%></li>
				<% end %>
			</ul>
		</div>  
	<% end %>
  
  
  
  
  
  <div class="control-group">
    <%= f.label :nc_number,"Nº da NC", :class => "control-label" %>
	<div class="controls">
    	<%= f.text_field :nc_number,%>
	</div>
  </div>
  
  
  <div class="control-group">
    <%= f.label :start_date,"Data início", :class => "control-label" %>
	<div class="controls">
    	<%= f.text_field :start_date,:class=>"input-small"%>
	</div>
  </div>

  
  <div class="control-group">
    <%= f.label :end_date,"Data fim", :class => "control-label" %>
	<div class="controls">
    	<%= f.text_field :end_date,:class=>"input-small"%>
	</div>
  </div>
  
  
  <div class="control-group">
			<%= f.link_to_add :resources, :class=>"btn btn-success" do %>
				<i class="icon-plus"></i>
				<span>Novo recurso</span>
			<% end %>
		</div>
	
		<%= f.fields_for :resources do |resources_form|%>
		<%=  javascript_tag  do%>
				
		<%end%>
		<div class    = "control-group">
			<div class   = "controls">
				<span class = "help-inline">
					<%= resources_form.collection_select(:nature_id,Nature.order(:nd),:id, :nd, {:prompt => "Selecione uma natureza"}) %>
				</span>
				<span class = "help-inline">
				<%= resources_form.text_field :value, :class => "value",:placeholder=>"Valor" %>
				</span>
				
				<span class = "help-inline">
					<%= resources_form.link_to_remove  do %>
					<i class   = "icon-remove"></i> 
					<% end %>
				</span>
			</div>
		</div>
		<% end %>
  
  
  
	  <div class="form-actions">
	    <%= f.submit "Salvar Orçamento",:class => "btn btn-primary" %>
		<%= link_to 'Cancelar', budgets_path,:class => "btn" %>
	  </div>
<% end %>

app/views/budgets/edit.html.erb
<h3>Editar Orçamento</h3>

<%= render 'form' %>

app/views/budgets/index.html.erb
<h3>Lista de Orçamentos</h3>
<br/>

<div class="span11">
	
	<%= link_to new_budget_path, :title => "Novo Orçamento",:class => "btn" do %>
			<i class="icon-plus"></i>&nbspNovo Orçamento
	<% end %>
			
</div>

<br/>
<br/>

<div class="span11">
<table class="table table-striped" >
  <tr>
    <th>Nº da NC</th>
    <th>Valor do Orçamento</th>
	<th>Data início</th>
	<th>Data fim</th>
    <th>Opções</th>
    
  </tr>

<% @budgets.each do |budget| %>
  <tr>
    <td><%= budget.nc_number %></td>
    <td><%= real_format(budget.total)%></td>
	<td><%= budget.start_date.strftime("%d/%m/%Y")%></td>
	<td><%= budget.end_date.strftime("%d/%m/%Y")%></td>
	<td>
		<ul>
			
			<li class="icon-edit" title="Editar">
				<%=link_to content_tag(:i,nil,:class=>"icon-edit"),edit_budget_path(budget)%>
			</li>
			
			<li class="icon-remove" title="Excluir">
				<%=link_to content_tag(:i,nil,:class=>"icon-remove"),budget, method: :delete, data: { confirm: 'Tem certeza que deseja excluir o orçamento selecionado?' }%>
			</li>
		</ul>
	</td>
  </tr>
<% end %>
</table>

<br />

</div>

app/views/budgets/new.html.erb
<h3>Novo Orçamento</h3>

<%= render 'form' %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nc number:</b>
  <%= @budget.nc_number %>
</p>

<p>
  <b>Start date:</b>
  <%= @budget.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @budget.end_date %>
</p>


<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>