config/routes.rb
OrcamentoControlIfba::Application.routes.draw do

  devise_for :users
  
  resources :home do 
    get :rectory_index, :on => :collection
    get :unit_index, :on => :collection
  end
  resources :resources do
    
    get :detail, :to => "resources#detail"
    
    resources :devolutions
    
    resources :transfers do
      
      resources :devolution_transfers
      
      resources :effort_transfers do
        resources :payment_transfers
      end
    end
    
    resources :efforts do
      resources :payments
    end
  end
  
  resources :budgets

  resources :natures

  resources :units
  root :to => "home#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    
    @budget = Budget.find_by_end_date(Budget.maximum(:end_date))
    
    if current_user.unit && !@budget.nil? 
      @transfers = Transfer.joins(:resource).where("resources.budget_id =:budget_id and unit_id = :unit_id",{:budget_id=>@budget.id,:unit_id=>current_user.unit.id})
    end
    
  end
  
  def rectory_index
    
    @budget = Budget.find_by_end_date(Budget.maximum(:end_date))
    
  end
  
  def unit_index
    
    @budget = Budget.find_by_end_date(Budget.maximum(:end_date))
    
    if current_user.unit && !@budget.nil? 
      @transfers = Transfer.joins(:resource).where("resources.budget_id =:budget_id and unit_id = :unit_id",{:budget_id=>@budget.id,:unit_id=>current_user.unit.id})
    end
    
  end
  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
            <h1>Bem Vindo ao SAF</h1>
			<br/>
            <p>Sistema de acompanhamento financeiro do programa bolsa formação PRONATEC do IF BAIANO.</p>
			<br/>
			<%if current_user.unit.nil? %>
				<%if @budget.nil?%>
					<p>Não existem orçamentos no sistema &nbsp;&nbsp; <%= link_to 'crie agora', new_budget_path,:class=>'btn btn-primary btn-large' %></p>
				<%else%>
					<p><%= link_to 'clique aqui' ,rectory_index_home_index_path,:class=>'btn btn-primary btn-large' %> para começar! </p>
				<%end%>
			<%end%>
			
			<%if current_user.unit%>
			
				<%if @transfers.size == 0 %>
					<p>Ainda não existem sub-repasses para a sua unidade.</p>
				<%else%>
					<p>Existem <%=@transfers.size%> sub-repasses para a sua unidade, <%= link_to 'clique aqui' ,unit_index_home_index_path %> para começar. </p>
				<%end%>
				
			<%end%>
            
          </div>

app/views/home/rectory_index.html.erb
<%=  javascript_tag  do%>

	function showDetail(url){
		$("#divDetail").load(url);
		$("#divDetail").modal();
	}

<%end%>


<div class="span11">
	<h3>Orçamento <%=@budget.start_date.strftime("%d/%m/%Y")%> - <%=@budget.end_date.strftime("%d/%m/%Y")%></h3>
</div>
<br/>
<br/>
<br/>


<div class="span12">
	<ul class="unstyled">
		<li><strong>Número da NC : </strong><%=@budget.nc_number%></li>
		<li><strong>Valor : </strong><%=real_format(@budget.total)%></li>
	</ul>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="span11">
<table class="table table-striped" >
  <tr>
    <th>Natureza</th>
    <th>Valor</th>
	<th>Gasto</th>
	<th>Saldo</th>
    <th>Opções</th>
    
  </tr>

	<% @budget.resources.each do |r| %>
  <tr>
    <td><%= r.nature.nd %></td>
    <td><%= real_format(r.value)%></td>
	<td><%= real_format(r.total_spending)%></td>
	<td><%= real_format(r.balance)%></td>
	<td>
		<ul>
			
			<li class="icon-list-alt" title="Resumo">
				<a href="#" onclick="showDetail('<%=resource_detail_path(r)%>');"><i class="icon-list-alt"></i></a>
			</li>
			
			<li class="icon-edit" title="Detalhes">
				<%=link_to content_tag(:i,nil,:class=>"icon-edit"),r%>
			</li>
		</ul>
	</td>
  </tr>
	<%end%>
</table>

<br />
<div id='divDetail' class="modal hide fade in"></div>
</div>

app/views/home/unit_index.html.erb
<div class="span11">
	<h3>Orçamento <%=@budget.start_date.strftime("%d/%m/%Y")%> - <%=@budget.end_date.strftime("%d/%m/%Y")%></h3>
</div>
<br/>
<br/>
<br/>


<div class="span12">
	<ul class="unstyled">
		<li><strong>Número da NC : </strong><%=@budget.nc_number%></li>
		<li><strong>Valor : </strong><%=real_format(@budget.total)%></li>
	</ul>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="span11">
	<strong><p>Sub Repasses</p></strong>
<table class="table table-striped" >
  <tr>
    <th>Natureza</th>
	<th>Número</th>
    <th>Valor</th>
	<th>Data</th>
    <th>Opções</th>
    
  </tr>

	<% @transfers.each do |t| %>
  <tr>
    <td><%= t.resource.nature.nd %></td>
	<td><%= t.identification %></td>
    <td><%= real_format(t.value)%></td>
	<td><%= t.date.strftime("%d/%m/%Y")%></td>
	<td>
		<ul>
			
			<li class="icon-edit" title="Detalhes">
				<%=link_to content_tag(:i,nil,:class=>"icon-edit"), resource_transfer_path(t.resource,t)%>
			</li>
		</ul>
	</td>
  </tr>
	<%end%>
</table>

<br />
<div id='divDetail' class="modal hide fade in"></div>
</div>