config/routes.rb
OrcamentoControlIfba::Application.routes.draw do

  devise_for :users
  
  resources :home do 
    get :rectory_index, :on => :collection
    get :unit_index, :on => :collection
  end
  resources :resources do
    
    get :detail, :to => "resources#detail"
    
    resources :devolutions
    
    resources :transfers do
      
      resources :devolution_transfers
      
      resources :effort_transfers do
        resources :payment_transfers
      end
    end
    
    resources :efforts do
      resources :payments
    end
  end
  
  resources :budgets

  resources :natures

  resources :units
  root :to => "home#index"
  
end

app/views/resources/_devolutions.html.erb
	<div class="row-fluid">
		<div class="span10">
			
			<%= link_to new_resource_devolution_path(resource), :title => "Nova Devolução",:class => "btn",:remote => true do %>
					<i class="icon-plus"></i>&nbspNova Devolução
			<% end %>
		</div>
	</div>
	<br/>
	<br/>
	<div id='divNovaDevolucao' class="modal hide fade in"></div>
	
	
	<div class="row-fluid">
		<div class="span10">
			<div id="devolutions">
				<% resource.devolutions.each do |devolution| %>
					<%=render(:partial => 'devolutions/item_devolution', :locals => {:devolution => devolution} )%>
				<%end%>
			</div>
		</div>
	</div>

app/views/resources/_efforts_payments.html.erb
	<div class="row-fluid">
		<div class="span10">
			
			<%= link_to new_resource_effort_path(resource), :title => "Novo Empenho",:class => "btn",:remote => true do %>
					<i class="icon-plus"></i>&nbspNovo Empenho
			<% end %>
					
		</div>
	</div>
	<br/>
	<br/>
	<div id='divNovoEmpenho' class="modal hide fade in"></div>
	
	
	<div id='divNovoPagamento' class="modal hide fade in"></div>
	
	<div class="row-fluid">
		<div class="span10">
			<div id="efforts">
				<% resource.efforts.each do |effort| %>
					<%=render(:partial => 'efforts/item_effort', :locals => {:effort => effort} )%>
				<%end%>
			</div>
		</div>
	</div>

app/views/resources/_sub_transfer.html.erb
	<div class="row-fluid">
		<div class="span10">
			
			<%= link_to new_resource_transfer_path(resource), :title => "Novo Sub Repasse",:class => "btn",:remote => true do %>
					<i class="icon-plus"></i>&nbspNovo Sub Repasse
			<% end %>
		</div>
	</div>
	<br/>
	<br/>
	<div id='divNovoSubRepasse' class="modal hide fade in"></div>
	
	
	<div class="row-fluid">
		<div class="span10">
			<div id="transfers">
				<% resource.transfers.each do |transfer| %>
					<%=render(:partial => 'transfers/item_transfer', :locals => {:transfer => transfer} )%>
				<%end%>
			</div>
		</div>
	</div>

app/views/resources/detail.html.erb
<div class="modal-header">	
	<button data-dismiss="modal" class="close" type="button">×</button>
	<h3>Resumo da Natureza <%=@resource.nature.nd%></h3>
</div>


<div class="modal-body">
	
	<div class="row-fluid">
	<div class="span12">
		<ul class="unstyled">
		<li><strong>Total de empenhos : </strong><%=real_format(@resource.total_efforts)%></li>
		<li><strong>Total de pagamentos : </strong><%=real_format(@resource.total_payments)%></li>
		</ul>
	</div>
	</div>
	<br/>
	<br/>
	
	<div class="row-fluid">
	<div class="span12">
		
		<%if @resource.transfers.empty?%>
			<strong>Não há Sub Repasses registrados para esta natureza!</strong>
		<%else%>
		<strong>Sub Repasses</strong>
		<table class="table table-striped" >
			<tr>
			    <th>NC</th>
				<th>Campus</th>
			    <th>Valor</th>
				<th>Devolvido</th>
			</tr>
			
			<% @resource.transfers.each do |t| %>
			  <tr>
			    <td><%= t.identification %></td>
			    <td><%= t.unit.name%></td>
				<td><%= real_format(t.value)%></td>
				<td><%= real_format(t.total_devolutions)%></td>
			  </tr>
			<%end%>
			<tr>
				<td colspan="2"><strong>Total</strong></td>
				<td><%= real_format(@resource.total_transfers)%></td>
				<td><%= real_format(@resource.total_devolutions_transfers)%></td>
			</tr>

			
		</table>
		<%end%>
	</div>
	</div>
	
</div>

<div class="modal-footer">
	
	<a data-dismiss="modal" class="btn" href="#">Fechar</a>

</div>		

	
	

app/views/resources/show.html.erb
<%=  javascript_tag  do%>

	function showPayment(url){
	
		$('#divNovoPagamento').empty();
		$("#divNovoPagamento").load(url);
		$("#divNovoPagamento").modal();
	}

<%end%>

<div class="row-fluid">
	<div class="span10">
		<h3>Orçamento <%=@resource.budget.start_date.strftime("%d/%m/%Y")%> - <%=@resource.budget.end_date.strftime("%d/%m/%Y")%></h3>
	</div>
</div>

<div class="row-fluid">
	<div class="span10">
		<ul class="unstyled">
			<li><strong>Natureza : </strong><%=@resource.nature.nd%></li>
			<li><strong>Valor : </strong><%=real_format(@resource.value)%></li>
			<li id="resource_balance_<%=@resource.id%>">
				<%=balance(@resource.balance)%>
			</li>
		</ul>
	</div>
</div>
<br/>
<ul class="nav nav-tabs">
	<li class="active"><a href="#effortPayments" data-toggle="tab">Pagamentos</a></li>
	<li><a href="#subTransfer" data-toggle="tab">Sub Repasses</a></li>
	<li><a href="#devolutions" data-toggle="tab">Devoluções</a></li>
</ul>


<div class="tab-content">
<div class="tab-pane active" id="effortPayments">
	<%=render(:partial => 'efforts_payments', :locals => {:resource => @resource} )%>
</div>
<div class="tab-pane" id="subTransfer">
	<%=render(:partial => 'sub_transfer', :locals => {:resource => @resource} )%>
</div>

<div class="tab-pane" id="devolutions">
	<%=render(:partial => 'devolutions', :locals => {:resource => @resource} )%>
</div>
</div>