config/routes.rb
OrcamentoControlIfba::Application.routes.draw do

  devise_for :users
  
  resources :home do 
    get :rectory_index, :on => :collection
    get :unit_index, :on => :collection
  end
  resources :resources do
    
    get :detail, :to => "resources#detail"
    
    resources :devolutions
    
    resources :transfers do
      
      resources :devolution_transfers
      
      resources :effort_transfers do
        resources :payment_transfers
      end
    end
    
    resources :efforts do
      resources :payments
    end
  end
  
  resources :budgets

  resources :natures

  resources :units
  root :to => "home#index"
  
end

app/models/transfer.rb
#encoding: utf-8
class Transfer < ActiveRecord::Base
  attr_accessible :resource_id, :unit_id, :value,:identification,:date,:obs
  belongs_to :resource
  belongs_to :unit
  has_many :effort_transfers
  has_many :devolution_transfers
  
  validates_presence_of :unit_id, :message => " deve ser preenchido"
  validates_presence_of :identification, :message => " deve ser preenchido"
  validates_presence_of :date, :message => " deve ser preenchida"
  validates_presence_of :value, :message => " deve ser preenchido"
  validates_numericality_of :value, :greater_than => 0,:message => " deve ser maior que zero"
  validate :has_balance
  
  def value=(_value)
    self[:value]=  _value.sub(".","").sub(",",".")
  end
  
  def total_efforts
    total = 0
    for effort in effort_transfers
      total = total + effort.value
    end
    
    total
  end
  
  def total_devolutions
    total = 0
    for devolution in devolution_transfers
      total = total + devolution.value
    end
    
    total
  end
  
   def balance
    value - self.total_efforts - self.total_devolutions 
  end
  
  private 
  def has_balance
    
    if (!value.nil? && (resource.balance < value))
      errors.add("O"," Valor do Sub Repasse ultrapassa o saldo do crédito desta natureza.")
    end
    
  end
  
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  
  def index
    @resource = Resource.find(params[:resource_id])
    @transfers = Transfer.find_all_by_unit_id(params[:unit_id])
    
  end
  
  def show
    
    @transfer = Transfer.find(params[:id])

    respond_to do |format|
      format.html
    end

  end

  
   def create
     @transfer = Transfer.new(params[:transfer])
     @transfer.resource_id = params[:resource_id]
     
    respond_to do |format|
      if @transfer.save
        @resource = Resource.find(params[:resource_id])
        format.js
      else
        @resource = Resource.find(params[:resource_id])
        format.js
      end
    end
  end

  def new
    @resource = Resource.find(params[:resource_id])
    @transfer = Transfer.new
    
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    
    @transfer = Transfer.find(params[:id])
    @transfer.destroy
    @resource = Resource.find(params[:resource_id])
    respond_to do |format|
      format.js
    end
  end
  
end

app/helpers/transfers_helper.rb
#encoding: utf-8
module TransfersHelper
  
  def transfer_pt(name)
      
      attr = name.to_s
      case attr
      when "value"
        attr = "Valor"
      when "identification"
        attr = "Número"
      when "date"
        attr = "Data"
      when "unit_id"
        attr = "Campus"
      end
      
    
     attr
    
  end
  
end

app/views/transfers/_devolutions.html.erb
	<div class="row-fluid">
		<div class="span10">
			
			<%= link_to new_resource_transfer_devolution_transfer_path(transfer.resource,transfer), :title => "Nova Devolução",:class => "btn",:remote => true do %>
					<i class="icon-plus"></i>&nbspNova Devolução
			<% end %>
		</div>
	</div>
	<br/>
	<br/>
	<div id='divNovaDevolucao' class="modal hide fade in"></div>
	
	
	<div class="row-fluid">
		<div class="span10">
			<div id="devolutions">
				<% transfer.devolution_transfers.each do |devolution| %>
					<%=render(:partial => 'devolution_transfers/item_devolution', :locals => {:devolution => devolution} )%>
				<%end%>
			</div>
		</div>
	</div>

app/views/transfers/_efforts_payments.html.erb
	<div class="row-fluid">
		<div class="span10">
			
			<%= link_to new_resource_transfer_effort_transfer_path(transfer.resource,transfer), :title => "Novo Empenho",:class => "btn",:remote => true do %>
					<i class="icon-plus"></i>&nbspNovo Empenho
			<% end %>
					
		</div>
	</div>
	<br/>
	<br/>
	<div id='divNovoEmpenho' class="modal hide fade in"></div>
	
	
	<div id='divNovoPagamento' class="modal hide fade in"></div>
	
	<div class="row-fluid">
		<div class="span10">
			<div id="efforts">
				<% transfer.effort_transfers.each do |effort| %>
					<%=render(:partial => 'effort_transfers/item_effort', :locals => {:effort => effort} )%>
				<%end%>
			</div>
		</div>
	</div>

app/views/transfers/_form.js.erb
$('#divNovoSubRepasse').html(" <%= escape_javascript( render(:partial => 'form_h', :format => "html")) %>");

app/views/transfers/_form_h.html.erb
<%=  javascript_tag  do%>
	
jQuery(function($) {
	
	$('#transfer_value').maskMoney({decimal:",",thousands:"."});
    $('#transfer_date').datepicker({
      yearRange     : 'c-0:c+10',
      showButtonPanel  : false,
      numberOfMonths  : 1,
      stepMonths    : 1,
	  dateFormat : 'dd/mm/yy',
	  dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
      monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
      hideIfNoPrevNext: true
    });
});
	
	
<%end%>

<div class="modal-header">	
	<button data-dismiss="modal" class="close" type="button">×</button>
	<h3>Sub Repasse</h3>
</div>

<%= form_for([@resource,@transfer],:remote => true,:html =>{:class => "form-horizontal", :style => "margin:0"}) do |f| %>
<div class="modal-body">
	
	
	<% if @transfer.errors.any? %>
			<div class="alert alert-error">
				<a class="close" data-dismiss="alert" href="#">×</a>
				<ul class="unstyled">
					
					<% @transfer.errors.each do |attribute,msg| %>
						<li> <%=transfer_pt(attribute) + msg%></li>
					<% end %>
				</ul>
			</div>
			
		<% end %>
	
	
	<div class="control-group">
		<%= f.label :unit_id,"Campus",:class=> "control-label" %>
		<div class="controls">
			<%= f.collection_select(:unit_id,Unit.order(:name),:id, :name, {:prompt => "Selecione um campus"}) %>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :identification,"Número",:class=> "control-label" %>
		<div class="controls">
			<%= f.text_field :identification%>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :date,"Data",:class=> "control-label" %>
		<div class="controls">
			<%= f.text_field :date,:class=> "input-small"%>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :value,"valor",:class=> "control-label" %>
		<div class="controls">
			<%= f.text_field :value%>
		</div>
	</div>
	
	<div class="control-group">
		<%= f.label :obs, "Observação",:class=> "control-label" %>
		<div class="controls">
			<%= f.text_area :obs,:class => "input-xlarge",:rows =>3%>
		</div>
	</div>
	
</div>

<div class="modal-footer">
	<%= f.submit "Ok",:class => "btn btn-primary" %>
	<a data-dismiss="modal" class="btn" href="#">Fechar</a>

</div>		
<% end %>
	
	

app/views/transfers/_item_transfer.html.erb
<div class="row-fluid" id="transfer_<%=transfer.id%>">
	
<div class="well span12">
	
	<%=link_to content_tag(:i,nil,:class=>"icon-remove"),resource_transfer_path(transfer.resource,transfer),:class=>"close",:remote=>true,:method=> :delete,:confirm => 'Tem certeza que deseja remover o sub-repasse selecionado ?'%>
	<h3>Sub Repasse <%=transfer.identification%></h3>
	<p>Campus : <%=transfer.unit.name%></p>
	<p>Data : <%=transfer.date.strftime("%d/%m/%Y")%></p>
	<p>Valor : <%=real_format(transfer.value)%></p>
	<p>Devolvido : <%=real_format(transfer.total_devolutions)%></p>
	
	<p>
		<%= link_to resource_transfer_path(transfer.resource,transfer), :title => "Detalhes",:class => "btn btn-success" do %>
			<i class="icon-plus"></i>&nbsp;Detalhes
		<% end %>
	</p>
</div>

</div>

app/views/transfers/create.js.erb
<% if @transfer.errors.any? %>
	<%= render :partial => 'form' %>
<% else %>
	$('#divNovoSubRepasse').modal('hide');
	$('#divNovoSubRepasse').empty();
	
	$('#transfers').append("<%= escape_javascript(render(:partial => 'item_transfer', :locals => {:transfer => @transfer} )) %>");
	$('#resource_balance_<%=@resource.id%>').html("<%=balance(@resource.balance)%>");
	$('html, body').animate({
    	scrollTop: $("#transfer_<%=@transfer.id%>").offset().top
	}, 2000);
	
<% end %>

app/views/transfers/destroy.js.erb
$('#transfer_<%=@transfer.id%>').html("");
$('#resource_balance_<%=@resource.id%>').html("<%=balance(@resource.balance)%>")

app/views/transfers/index.html.erb
<div class="span11">
	<h3>Orçamento <%=@resource.budget.start_date.strftime("%d/%m/%Y")%> - <%=@resource.budget.end_date.strftime("%d/%m/%Y")%></h3>
</div>
<br/>
<br/>
<br/>


<div class="span12">
	<ul class="unstyled">
		<li><strong>Sub Repasses </strong></li>
	</ul>
</div>
<br/>
<br/>

<div class="span11">
<table class="table table-striped" >
  <tr>
    <th>Natureza</th>
	<th>NC</th>
    <th>Valor</th>
	<th>Gasto</th>
	<th>Saldo</th>
    <th>Opções</th>
    
  </tr>

	<% @transfers.each do |t| %>
  <tr>
    <td><%= t.resource.nature.nd %></td>
	<td><%= t.identification %></td>
    <td><%= t.value%></td>
	<td><%= ""%></td>
	<td><%= ""%></td>
	<td>
		<ul>
			
			<li class="icon-edit" title="Editar">
				
			</li>
			
			<li class="icon-edit" title="Detalhes">
				<%=link_to content_tag(:i,nil,:class=>"icon-edit"),[t.resource,t]%>
			</li>
		</ul>
	</td>
  </tr>
	<%end%>
</table>

<br />

</div>

app/views/transfers/new.js.erb
$("#divNovoSubRepasse")
.html(" <%= escape_javascript( render(:partial => 'form_h', :format => "html")) %>")
.modal();

app/views/transfers/show.html.erb
<%=  javascript_tag  do%>

	function showPayment(url){
	
		$('#divNovoPagamento').empty();
		$("#divNovoPagamento").load(url);
		$("#divNovoPagamento").modal();
	}

<%end%>

<div class="row-fluid">
	<div class="span10">
		<h3>Orçamento <%=@transfer.resource.budget.start_date.strftime("%d/%m/%Y")%> - <%=@transfer.resource.budget.end_date.strftime("%d/%m/%Y")%></h3>
	</div>
</div>
<br/>
<br/>
<div class="row-fluid">
	<div class="span10">
		<ul class="unstyled">
			<li><strong>Campus : </strong><%=@transfer.unit.name%></li>
			<li><strong>NC : </strong><%=@transfer.identification%></li>
			<li><strong>Natureza : </strong><%=@transfer.resource.nature.nd%></li>
			<li><strong>Valor : </strong><%=real_format(@transfer.value)%></li>
			<li id="transfer_balance_<%=@transfer.id%>">
				<%=balance(@transfer.balance)%>
			</li>
		</ul>
	</div>
</div>
<br/>
<ul class="nav nav-tabs">
	<li class="active"><a href="#effortPayments" data-toggle="tab">Pagamentos</a></li>
	<li><a href="#devolutions" data-toggle="tab">Devoluções</a></li>
</ul>


<div class="tab-content">
<div class="tab-pane active" id="effortPayments">
	<%=render(:partial => 'efforts_payments', :locals => {:transfer => @transfer} )%>
</div>
<div class="tab-pane" id="devolutions">
	<%=render(:partial => 'devolutions', :locals => {:transfer => @transfer} )%>
</div>
</div>